# Generated by Django 5.0.7 on 2024-08-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('red', 'Czerwony'), ('blue', 'Niebieski'), ('green', 'Zielony'), ('orange', 'Pomarańczowy'), ('purple', 'Fioletowy'), ('yellow', 'Żółty'), ('gray', 'Grafitowy')], default='blue', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='importance',
            field=models.CharField(choices=[('lime', 'Ważne (Limonkowy)'), ('cyan', 'Średnie (Cyjan)'), ('pink', 'Mało ważne (Różowy)')], default='cyan', max_length=10),
        ),
    ]
