# Generated by Django 5.0.7 on 2024-09-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0003_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='text',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='event',
            name='importance',
            field=models.CharField(choices=[('lime', 'Ważne (Limonkowy)'), ('cyan', 'Średnie (Cyjan)'), ('pink', 'Mało ważne (Różowy)'), ('', 'Standardowy (Grafitowy)')], default='cyan', max_length=10),
        ),
    ]
